# Generated by Django 5.0.6 on 2024-06-03 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carro",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("marca", models.CharField(max_length=50)),
                ("modelo", models.CharField(max_length=50)),
                ("motor", models.CharField(max_length=50)),
                ("cilindros", models.CharField(max_length=50)),
                ("valvulas", models.CharField(max_length=20)),
                ("potencia", models.CharField(max_length=50)),
                ("kilometraje", models.IntegerField()),
                ("año", models.IntegerField()),
                ("precio", models.IntegerField()),
                ("descripcion", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("lujo", "Lujo"),
                            ("variado", "Variado"),
                        ],
                        max_length=50,
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("image", models.ImageField(null=True, upload_to="generator/images/")),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
                ("num_puertas", models.IntegerField()),
                (
                    "transmision",
                    models.CharField(
                        choices=[("manual", "Manual"), ("automatico", "Automático")],
                        max_length=50,
                    ),
                ),
                ("num_asientos", models.IntegerField()),
                (
                    "combustible",
                    models.CharField(
                        choices=[
                            ("electrico", "Eléctrico"),
                            ("gasolina", "Gasolina"),
                            ("diesel", "Diésel"),
                            ("hibrido", "Híbrido"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "Carro",
            },
        ),
        migrations.CreateModel(
            name="ImagenCarro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="generator/images/"
                    ),
                ),
                (
                    "carro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="generator.carro",
                    ),
                ),
            ],
            options={
                "db_table": "ImagenCarro",
            },
        ),
    ]
