# Generated by Django 5.0.6 on 2024-06-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carro",
            name="modelo",
            field=models.CharField(max_length=100),
        ),
    ]
